name: gh_issue_tracker
description: The flutter Project issue tracker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async_redux: ^6.0.2
  cupertino_icons: ^0.1.3
  collection: ^1.14.13
  flutter_svg: ^0.19.1
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/