name: gh_issue_tracker
description: The flutter project issue tracker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async_redux: ^9.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.2
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.5.1
  collection: ^1.15.0
  flutter_svg: ^0.19.3
  flutter:
    sdk: flutter
  http: ^0.12.2
  intl: ^0.16.1
  timeago: ^3.0.2
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/